Repository DDD-Community/DDD-12-MOYORAK-API, pull requests merged in 2025-07, with the labels that each got.

#134 feat: #128 팀 ID 혹은 이름을 통해 팀 정보 조회할 수 있는 API 추가
  src/main/java/com/moyorak/api/team/controller/TeamController.java
  src/main/java/com/moyorak/api/team/domain/TeamSearch.java
  src/main/java/com/moyorak/api/team/dto/TeamSearchListResponse.java
  src/main/java/com/moyorak/api/team/dto/TeamSearchRequest.java
  src/main/java/com/moyorak/api/team/dto/TeamSearchResponse.java
  src/main/java/com/moyorak/api/team/repository/TeamRepository.java
  src/main/java/com/moyorak/api/team/service/TeamService.java
  src/test/java/com/moyorak/api/team/dto/TeamSearchRequestTest.java
Labels: ✨ Feature

#139 Feature/134 식당상세정보 팀원 리뷰 조회 기능 개발
  src/main/java/com/moyorak/api/review/domain/Review.java
  src/main/java/com/moyorak/api/review/domain/ReviewPhotoPaths.java
  src/main/java/com/moyorak/api/review/dto/ReviewPhotoPath.java
  src/main/java/com/moyorak/api/review/dto/ReviewWithUserProjection.java
  src/main/java/com/moyorak/api/review/repository/ReviewPhotoRepository.java
  src/main/java/com/moyorak/api/review/repository/ReviewRepository.java
  src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
  src/main/java/com/moyorak/api/review/service/ReviewService.java
  src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantReviewRequest.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantReviewResponse.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java
  src/test/java/com/moyorak/api/review/dto/ReviewWithUserProjectionFixture.java
  src/test/java/com/moyorak/api/review/service/ReviewPhotoServiceTest.java
  src/test/java/com/moyorak/api/review/service/ReviewServiceTest.java
  src/test/java/com/moyorak/api/team/dto/TeamRestaurantReviewRequestFixture.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java
Labels: ✨ Feature

#140 feat: #137 팀 맛집 모든 위치 조회
  src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantLocation.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantLocationsResponse.java
  src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java
Labels: ✨ Feature

#144 feat: #141 초대 링크 생성
  src/main/java/com/moyorak/api/team/controller/TeamInvitationController.java
  src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
  src/main/java/com/moyorak/api/team/domain/InvitationToken.java
  src/main/java/com/moyorak/api/team/domain/TeamInvitation.java
  src/main/java/com/moyorak/api/team/domain/TeamUserNotFoundException.java
  src/main/java/com/moyorak/api/team/dto/TeamInvitationCreateResponse.java
  src/main/java/com/moyorak/api/team/repository/TeamInvitationRepository.java
  src/main/java/com/moyorak/api/team/repository/TeamUserRepository.java
  src/main/java/com/moyorak/api/team/service/TeamInvitationService.java
  src/test/java/com/moyorak/api/team/service/TeamInvitationServiceTest.java
Labels: ✨ Feature

#146 팀 맛집 리뷰 사진 조회
  src/main/java/com/moyorak/api/review/dto/PhotoPath.java
  src/main/java/com/moyorak/api/review/repository/ReviewPhotoRepository.java
  src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
  src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantReviewPhotoRequest.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
  src/test/java/com/moyorak/api/review/service/ReviewPhotoServiceTest.java
  src/test/java/com/moyorak/api/team/dto/TeamRestaurantReviewPhotoRequestFixture.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java
Labels: ✨ Feature

#147 fear: #143 초대 링크를 통해 팀 회사 정보 조회하기
  src/main/java/com/moyorak/api/team/controller/TeamInvitationController.java
  src/main/java/com/moyorak/api/team/domain/TeamInvitation.java
  src/main/java/com/moyorak/api/team/domain/TeamInvitationTokenNotFoundException.java
  src/main/java/com/moyorak/api/team/dto/TeamInvitationDetailResponse.java
  src/main/java/com/moyorak/api/team/repository/TeamInvitationRepository.java
  src/main/java/com/moyorak/api/team/service/TeamInvitationService.java
  src/test/java/com/moyorak/api/team/domain/TeamInvitationFixture.java
  src/test/java/com/moyorak/api/team/domain/TeamInvitationTest.java
  src/test/java/com/moyorak/api/team/service/TeamInvitationServiceTest.java
Labels: ✨ Feature

#163 feature/158 회사 저장, 검색 기능 개발
  src/main/java/com/moyorak/api/company/controller/CompanyController.java
  src/main/java/com/moyorak/api/company/domain/Company.java
  src/main/java/com/moyorak/api/company/domain/CompanySearch.java
  src/main/java/com/moyorak/api/company/dto/CompanySaveRequest.java
  src/main/java/com/moyorak/api/company/dto/CompanySearchListResponse.java
  src/main/java/com/moyorak/api/company/dto/CompanySearchRequest.java
  src/main/java/com/moyorak/api/company/dto/CompanySearchResponse.java
  src/main/java/com/moyorak/api/company/repository/CompanyRepository.java
  src/main/java/com/moyorak/api/company/repository/CompanySearchRepository.java
  src/main/java/com/moyorak/api/company/service/CompanyService.java
  src/test/java/com/moyorak/api/company/domain/CompanyFixture.java
  src/test/java/com/moyorak/api/company/domain/CompanySearchFixture.java
  src/test/java/com/moyorak/api/company/dto/CompanySearchRequestTest.java
  src/test/java/com/moyorak/api/company/service/CompanyServiceTest.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantServiceTest.java
Labels: ✨ Feature

#160 feat: #154 본인 검색 기록 조회
  src/main/java/com/moyorak/api/history/controller/SearchHistoryController.java
  src/main/java/com/moyorak/api/history/dto/SearchHistoryListResponse.java
  src/main/java/com/moyorak/api/history/dto/SearchHistoryRequest.java
  src/main/java/com/moyorak/api/history/dto/SearchHistoryResponse.java
  src/main/java/com/moyorak/api/history/repository/SearchHistoryRepository.java
  src/main/java/com/moyorak/api/history/service/SearchHistoryService.java
  src/test/java/com/moyorak/api/history/domain/SearchHistoryFixture.java
  src/test/java/com/moyorak/api/history/service/SearchHistoryServiceTest.java
Labels: ✨ Feature

#171 feat: #169 팀 맛집 상세 조회 시 본인 조회 기록에 저장
  src/main/java/com/moyorak/api/history/domain/ViewHistory.java
  src/main/java/com/moyorak/api/history/service/HistoryEventHandler.java
  src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantViewEvent.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantEventPublisher.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantServiceTest.java
Labels: ✨ Feature

#172 feat: #161 본인 팀 맛집 검색 기록 삭제
  src/main/java/com/moyorak/api/history/controller/SearchHistoryController.java
  src/main/java/com/moyorak/api/history/domain/SearchHistory.java
  src/main/java/com/moyorak/api/history/repository/SearchHistoryRepository.java
  src/main/java/com/moyorak/api/history/service/SearchHistoryService.java
  src/test/java/com/moyorak/api/history/domain/SearchHistoryFixture.java
  src/test/java/com/moyorak/api/history/domain/SearchHistoryTest.java
  src/test/java/com/moyorak/api/history/service/SearchHistoryServiceTest.java
Labels: ✨ Feature

#173 refactor: #170 초대 링크 생성에서 토큰 생성으로 변경
  src/main/java/com/moyorak/api/team/controller/TeamInvitationController.java
  src/main/java/com/moyorak/api/team/dto/TeamInvitationCreateResponse.java
  src/main/java/com/moyorak/api/team/service/TeamInvitationService.java
  src/test/java/com/moyorak/api/team/service/TeamInvitationServiceTest.java
Labels: 🔨 Refactor

#174 feat: #162 본인 팀 맛집 상세 조회 기록 삭제
  src/main/java/com/moyorak/api/history/controller/ViewHistoryController.java
  src/main/java/com/moyorak/api/history/domain/ViewHistory.java
  src/main/java/com/moyorak/api/history/repository/ViewHistoryRepository.java
  src/main/java/com/moyorak/api/history/service/ViewHistoryService.java
  src/test/java/com/moyorak/api/history/domain/ViewHistoryFixture.java
  src/test/java/com/moyorak/api/history/domain/ViewHistoryTest.java
  src/test/java/com/moyorak/api/history/service/ViewHistoryServiceTest.java
Labels: ✨ Feature

#180 chore: #179 CORS 설정 추가
  src/main/java/com/moyorak/config/web/WebConfig.java
Labels: ⚙️ Setting

#181 chore: #157 환경변수 및 배포 스크립트 수정
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  src/main/resources/application-dev.yml
Labels: ⚙️ Setting

#182 chore: #157 환경 변수 관련 수정
  .github/workflows/deploy.yml
Labels: ⚙️ Setting

#183 chore: #157 환경 변수 호출 방법 env -> vars로 수정
  .github/workflows/deploy.yml
Labels: ⚙️ Setting

#178 feat: #177 리뷰 대기시간,서빙시간 조회
  src/main/java/com/moyorak/api/review/controller/ReviewController.java
  src/main/java/com/moyorak/api/review/domain/ReviewServingTime.java
  src/main/java/com/moyorak/api/review/domain/ReviewWaitingTime.java
  src/main/java/com/moyorak/api/review/dto/ReviewServingTimeResponse.java
  src/main/java/com/moyorak/api/review/dto/ReviewWaitingTimeResponse.java
  src/main/java/com/moyorak/api/review/repository/ReviewServingTimeRepository.java
  src/main/java/com/moyorak/api/review/repository/ReviewWaitingTimeRepository.java
  src/main/java/com/moyorak/api/review/service/ReviewService.java
  src/test/java/com/moyorak/api/review/domain/ReviewServingTimeFixture.java
  src/test/java/com/moyorak/api/review/domain/ReviewWaitingTimeFixture.java
  src/test/java/com/moyorak/api/review/service/ReviewServiceTest.java
Labels: ✨ Feature

#175 feat: #167 팀 가입 신청,승인 기능 개발
  src/main/java/com/moyorak/api/team/controller/TeamUserController.java
  src/main/java/com/moyorak/api/team/domain/TeamUser.java
  src/main/java/com/moyorak/api/team/repository/TeamRepository.java
  src/main/java/com/moyorak/api/team/repository/TeamSearchRepository.java
  src/main/java/com/moyorak/api/team/repository/TeamUserRepository.java
  src/main/java/com/moyorak/api/team/service/TeamJoinFacade.java
  src/main/java/com/moyorak/api/team/service/TeamService.java
  src/main/java/com/moyorak/api/team/service/TeamUserService.java
  src/test/java/com/moyorak/api/team/service/TeamUserServiceTest.java
Labels: ✨ Feature

#200 refactor: #199 회원 가입 후 응답으로 회원 id를 반환한다
  src/main/java/com/moyorak/api/auth/controller/UserController.java
  src/main/java/com/moyorak/api/auth/dto/OAuthResponse.java
  src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
  src/main/java/com/moyorak/api/auth/service/UserService.java
  src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
  src/main/java/com/moyorak/infra/orm/SecurityAuditorAware.java
Labels: 🔨 Refactor
