Repository DDD-Community/DDD-12-MOYORAK-API, pull requests merged in 2025-09, with the labels that each got.

#317 refactor:#316 내 리뷰 조회 시, 팀 맛집 정보 추가
  src/main/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjection.java
  src/main/java/com/moyorak/api/auth/dto/UserReviewResponse.java
  src/main/java/com/moyorak/api/auth/service/UserReviewFacade.java
  src/main/java/com/moyorak/api/review/domain/ReviewTimeLabels.java
  src/main/java/com/moyorak/api/review/repository/ReviewRepository.java
  src/main/java/com/moyorak/api/review/service/ReviewService.java
  src/test/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjectionFixture.java
  src/test/java/com/moyorak/api/auth/service/UserReviewFacadeTest.java
Labels: 🔨 Refactor

#319 refactor: #318 팀 역할 필드 추가
  src/main/java/com/moyorak/api/auth/controller/UserController.java
  src/main/java/com/moyorak/api/auth/dto/UserOrganisationResponse.java
  src/main/java/com/moyorak/api/team/service/TeamUserService.java
Labels: 🔨 Refactor

#321 refactor:#320 내 리뷰 조회 시, 팀 맛집 삭제 여부 추가
  src/main/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjection.java
  src/main/java/com/moyorak/api/auth/dto/UserReviewResponse.java
  src/main/java/com/moyorak/api/review/repository/ReviewRepository.java
  src/test/java/com/moyorak/api/auth/dto/ReviewWithUserAndTeamRestaurantProjectionFixture.java
Labels: 🔨 Refactor

#323 feat: #322 팀 매니저 양도 기능으로 변경
  src/main/java/com/moyorak/api/team/controller/TeamUserController.java
  src/main/java/com/moyorak/api/team/service/TeamUserManagementService.java
  src/test/java/com/moyorak/api/team/service/TeamUserManagementServiceTest.java
Labels: ✨ Feature

#326 chore: #325 회원 프로필 이미지 varchar(256) 에서 varchar(512)로 변경
  src/main/java/com/moyorak/api/auth/domain/User.java
Labels: 🔨 Refactor

#330 fix: #329 쿼리 수정
  src/main/java/com/moyorak/api/team/repository/TeamRepository.java
Labels: 🐞 Fix
