Repository DDD-Community/DDD-12-MOYORAK-API, pull requests merged in 2025-06, with the labels that each got.

#33 build: #31 AWS 인증 처리할 수 있도록 과정 추가
  .github/workflows/ecr-deploy.yml
Labels: 🌏 Deploy

#36 build: #34 불필요한 step 삭제
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#37 build: #34 Github Action IP 인바운드에 동적으로 추가할 수 있도록 step 추가
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#38 build: #34 EC2 내의 sh 실행하는 방식으로 변경
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#30 feat: #25 카카오 지도 api client 개발
  src/main/java/com/moyorak/api/restaurant/controller/RestaurantController.java
  src/main/java/com/moyorak/api/restaurant/dto/RestaurantResponse.java
  src/main/java/com/moyorak/api/restaurant/dto/RestaurantSearchRequest.java
  src/main/java/com/moyorak/api/restaurant/service/RestaurantService.java
  src/main/java/com/moyorak/config/exception/RootExceptionHandler.java
  src/main/java/com/moyorak/config/exception/ServerSideException.java
  src/main/java/com/moyorak/infra/client/RestClientConfig.java
  src/main/java/com/moyorak/infra/client/kakao/KakaoClientConfig.java
  src/main/java/com/moyorak/infra/client/kakao/KakaoSearcher.java
  src/main/java/com/moyorak/infra/client/kakao/KakoClient.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakaoMeta.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakaoPlace.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakaoSearchRequest.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakoSearchResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local-tepmlate.yml
Labels: ✨ Feature

#54 feat: #53 최초 회원 가입의 경우 기본 정보를 반환한다
  src/main/java/com/moyorak/api/auth/domain/User.java
  src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
  src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
  src/main/java/com/moyorak/config/security/CustomOAuth2UserService.java
Labels: ✨ Feature

#61 chore: #58 로그인 요청 시 JWT 필터에서 제외 되도록 조건 추가
  src/main/java/com/moyorak/config/security/JwtAuthenticationFilter.java
  src/test/java/com/moyorak/config/security/JwtAuthenticationFilterTest.java
Labels: 🔨 Refactor

#67 chore: #65 IP 변수 선언
  .github/workflows/add-inbound.yml
Labels: ⚙️ Setting

#68 chore: #65 인바운드 규칙 추가 후 로그 보이지 않도록 설정 추가
  .github/workflows/add-inbound.yml
Labels: ⚙️ Setting

#70 chore: #65 IP 정보는 동적으로 받을 수 있도록 변경
  .github/workflows/add-inbound.yml
Labels: ⚙️ Setting

#77 refactor: #72 아이피를 환경별 시크릿을 통해 가지고올 수 있도록 변경
  .github/workflows/add-inbound.yml
Labels: 🌏 Deploy

#78 fix: #72 PORT 변수 선언
  .github/workflows/add-inbound.yml
Labels: 🐞 Fix

#81 fix: #72 \ 추가
  .github/workflows/add-inbound.yml
Labels: 🐞 Fix

#94 feat: #63 배포 완료 여부 디스코드 웹훅으로 메세지 전송
  .github/workflows/deploy.yml
Labels: ✨ Feature, 🌏 Deploy

#93 feat: #85 회원 가입 기능을 개발합니다
  src/main/java/com/moyorak/api/auth/controller/UserController.java
  src/main/java/com/moyorak/api/auth/domain/Gender.java
  src/main/java/com/moyorak/api/auth/domain/User.java
  src/main/java/com/moyorak/api/auth/dto/SignUpRequest.java
  src/main/java/com/moyorak/api/auth/dto/SignUpResponse.java
  src/main/java/com/moyorak/api/auth/repository/UserRepository.java
  src/main/java/com/moyorak/api/auth/service/UserService.java
  src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
  src/main/java/com/moyorak/config/security/CustomOAuth2UserService.java
  src/main/java/com/moyorak/config/security/JwtAuthenticationFilter.java
  src/main/java/com/moyorak/config/security/SecurityConfig.java
  src/main/java/com/moyorak/infra/orm/SecurityAuditorAware.java
  src/test/java/com/moyorak/api/auth/domain/GenderTest.java
  src/test/java/com/moyorak/api/auth/dto/SignUpRequestFixture.java
  src/test/java/com/moyorak/api/auth/service/UserServiceTest.java
Labels: ✨ Feature

#108 feat: #104 도로명 지번 주소 모두 저장되도록 수정
  src/main/java/com/moyorak/api/restaurant/domain/Restaurant.java
  src/main/java/com/moyorak/api/restaurant/dto/RestaurantSaveRequest.java
  src/test/java/com/moyorak/api/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/moyorak/api/restaurant/domain/RestaurantFixture.java
  src/test/java/com/moyorak/api/restaurant/domain/RestaurantTest.java
  src/test/java/com/moyorak/api/restaurant/service/RestaurantServiceTest.java
Labels: 🔨 Refactor

#115 fix: #113 토큰 발급 endpoint 시큐리티 필터에서 처리되지 않도록 조건 추가
  src/main/java/com/moyorak/config/security/SecurityConfig.java
Labels: 🐞 Fix

#109 feat: #90 카카오 api 조회 수정
  src/main/java/com/moyorak/api/restaurant/controller/RestaurantController.java
  src/main/java/com/moyorak/api/restaurant/dto/RestaurantResponse.java
  src/main/java/com/moyorak/api/restaurant/dto/RestaurantSearchRequest.java
  src/main/java/com/moyorak/infra/client/kakao/KakaoClient.java
  src/main/java/com/moyorak/infra/client/kakao/KakaoClientConfig.java
  src/main/java/com/moyorak/infra/client/kakao/KakaoSearcher.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakaoPlace.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakaoSearchResponse.java
  src/main/java/com/moyorak/infra/client/kakao/dto/KakoSearchResponse.java
  src/test/java/com/moyorak/infra/client/kakao/KakaoSearcherTest.java
  src/test/java/com/moyorak/infra/client/kakao/dto/KakaoSearchResponseTest.java
Labels: 🔨 Refactor

#111 feat: #92 혼밥 상태 조회, 수정/저장 api 개발
  src/main/java/com/moyorak/api/auth/controller/UserDailyStateController.java
  src/main/java/com/moyorak/api/auth/domain/State.java
  src/main/java/com/moyorak/api/auth/domain/UserDailyState.java
  src/main/java/com/moyorak/api/auth/dto/UserDailyStateRequest.java
  src/main/java/com/moyorak/api/auth/dto/UserDailyStateResponse.java
  src/main/java/com/moyorak/api/auth/repository/UserDailyStateRepository.java
  src/main/java/com/moyorak/api/auth/service/UserDailyStateService.java
  src/test/java/com/moyorak/api/auth/domain/UserDailyStateFixture.java
  src/test/java/com/moyorak/api/auth/service/UserDailyStateServiceTest.java
Labels: ✨ Feature

#118 feat: #117 팀, 팀식당 엔티티 생성
  src/main/java/com/moyorak/api/team/domain/Team.java
  src/main/java/com/moyorak/api/team/domain/TeamPlace.java
Labels: ✨ Feature

#114 feat: #100 PresignedUrl 업로드 url 발급 받는 기능 추가
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  build.gradle.kts
  src/main/java/com/moyorak/api/image/controller/ImageController.java
  src/main/java/com/moyorak/api/image/dto/ImageSaveRequest.java
  src/main/java/com/moyorak/api/image/dto/ImageSaveResponse.java
  src/main/java/com/moyorak/api/image/service/ImageService.java
  src/main/java/com/moyorak/config/exception/BusinessException.java
  src/main/java/com/moyorak/infra/aws/s3/S3Adapter.java
  src/main/java/com/moyorak/infra/aws/s3/S3Config.java
  src/main/java/com/moyorak/infra/aws/s3/S3Properties.java
  src/main/resources/application-local-tepmlate.yml
  src/main/resources/application.yml
  src/test/java/com/moyorak/api/image/dto/ImageSaveRequestTest.java
  src/test/java/com/moyorak/infra/aws/s3/S3AdapterTest.java
Labels: ✨ Feature

#121 feat: #120 리뷰 테이블 생성
  src/main/java/com/moyorak/api/review/Review.java
  src/main/java/com/moyorak/api/review/ReviewPhoto.java
Labels: ✨ Feature
