Repository DDD-Community/DDD-12-MOYORAK-API, pull requests merged in 2025-08, with the labels that each got.

#198 refactor:#197 팀 맛집 상세 조회 누락 데이터 추가
  src/main/java/com/moyorak/api/review/domain/ReviewTimeLabels.java
  src/main/java/com/moyorak/api/review/domain/ReviewTimeRangeMapper.java
  src/main/java/com/moyorak/api/review/dto/LabelPair.java
  src/main/java/com/moyorak/api/review/dto/ReviewWithUserProjection.java
  src/main/java/com/moyorak/api/review/repository/ReviewRepository.java
  src/main/java/com/moyorak/api/review/service/ReviewService.java
  src/main/java/com/moyorak/api/team/controller/TeamRestaurantController.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantResponse.java
  src/main/java/com/moyorak/api/team/dto/TeamRestaurantReviewResponse.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantFacade.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java
  src/test/java/com/moyorak/api/review/dto/ReviewWithUserProjectionFixture.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantFacadeTest.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantServiceTest.java
Labels: 🔨 Refactor

#208 refactor: #207 OAuth 성공 시 클라이언트로 리다이렉트 하도록 수정
  src/main/java/com/moyorak/config/security/CustomOAuth2SuccessHandler.java
  src/main/java/com/moyorak/config/security/SecurityProperties.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🔨 Refactor

#215 chore: #214 클라이언트 https 관련 설정 추가
  src/main/resources/application-dev.yml
Labels: ⚙️ Setting

#219 refactor: #217 이미지 서비스 재사용을 위해 컴포넌트로 분리
  src/main/java/com/moyorak/api/image/ImageStore.java
  src/main/java/com/moyorak/api/image/service/ImageService.java
  src/test/java/com/moyorak/api/image/service/ImageStoreTest.java
Labels: 🔨 Refactor

#222 refactor: #220 팀 맛집 리뷰 이미지 경로 변환 코드 수정
  src/main/java/com/moyorak/api/image/ImageStore.java
  src/main/java/com/moyorak/api/image/service/ImageService.java
  src/main/java/com/moyorak/api/review/domain/ReviewPhotoPaths.java
  src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantReviewFacade.java
  src/test/java/com/moyorak/api/team/service/TeamRestaurantReviewFacadeTest.java
Labels: 🔨 Refactor

#224 refactor: #135 온보딩 과정을 Step별로 나눠 처리한다.
  src/main/java/com/moyorak/api/auth/dto/SignUpRequest.java
  src/main/java/com/moyorak/api/company/controller/CompanyController.java
  src/main/java/com/moyorak/api/team/controller/TeamController.java
  src/main/java/com/moyorak/config/security/JwtAuthenticationFilter.java
Labels: 🔨 Refactor

#235 feat:#232 팟, 팟 참가자 테이블 생성
  src/main/java/com/moyorak/api/party/domain/Party.java
  src/main/java/com/moyorak/api/party/domain/PartyAttendee.java
Labels: ✨ Feature

#236 feat: #233 회사의 위도, 경도를 조회한다.
  src/main/java/com/moyorak/api/company/controller/CompanyController.java
  src/main/java/com/moyorak/api/company/dto/CompanyPositionResponse.java
  src/main/java/com/moyorak/api/company/repository/CompanyRepository.java
  src/main/java/com/moyorak/api/company/service/CompanyService.java
  src/test/java/com/moyorak/api/company/service/CompanyServiceTest.java
Labels: ✨ Feature

#239 feat:#238 파티 목록 조회
  src/main/java/com/moyorak/api/party/controller/PartyController.java
  src/main/java/com/moyorak/api/party/domain/Party.java
  src/main/java/com/moyorak/api/party/domain/SelectionVoteInfo.java
  src/main/java/com/moyorak/api/party/dto/PartyAttendeeWithUserProfile.java
  src/main/java/com/moyorak/api/party/dto/PartyGeneralInfoProjection.java
  src/main/java/com/moyorak/api/party/dto/PartyListRequest.java
  src/main/java/com/moyorak/api/party/dto/PartyListResponse.java
  src/main/java/com/moyorak/api/party/dto/PartyListStore.java
  src/main/java/com/moyorak/api/party/dto/PartyRestaurantProjection.java
  src/main/java/com/moyorak/api/party/dto/PartyRestaurantResponse.java
  src/main/java/com/moyorak/api/party/repository/PartyAttendeeRepository.java
  src/main/java/com/moyorak/api/party/repository/PartyRepository.java
  src/main/java/com/moyorak/api/party/repository/PartyRestaurantRepository.java
  src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
  src/main/java/com/moyorak/api/party/service/PartyRestaurantService.java
  src/main/java/com/moyorak/api/party/service/PartyService.java
  src/main/java/com/moyorak/api/party/service/PartyVoteService.java
  src/test/java/com/moyorak/api/party/domain/PartyAttendeeFixture.java
  src/test/java/com/moyorak/api/party/domain/PartyAttendeeWithUserFixture.java
  src/test/java/com/moyorak/api/party/domain/PartyGeneralInfoProjectionFixture.java
  src/test/java/com/moyorak/api/party/domain/PartyRestaurantProjectionFixture.java
  src/test/java/com/moyorak/api/party/dto/PartyListRequestFixture.java
  src/test/java/com/moyorak/api/party/service/PartyFacadeTest.java
Labels: ✨ Feature

#242 feat: #237 파티 상세 조회
  src/main/java/com/moyorak/api/party/controller/PartyController.java
  src/main/java/com/moyorak/api/party/domain/RandomVoteInfo.java
  src/main/java/com/moyorak/api/party/domain/Vote.java
  src/main/java/com/moyorak/api/party/domain/VoteStatus.java
  src/main/java/com/moyorak/api/party/dto/PartyInfo.java
  src/main/java/com/moyorak/api/party/dto/PartyResponse.java
  src/main/java/com/moyorak/api/party/dto/RestaurantCandidate.java
  src/main/java/com/moyorak/api/party/dto/RestaurantCandidateResponse.java
  src/main/java/com/moyorak/api/party/dto/VoteDetail.java
  src/main/java/com/moyorak/api/party/dto/VoteInfo.java
  src/main/java/com/moyorak/api/party/dto/VoteResponse.java
  src/main/java/com/moyorak/api/party/dto/Voter.java
  src/main/java/com/moyorak/api/party/dto/VoterResponse.java
  src/main/java/com/moyorak/api/party/repository/PartyRepository.java
  src/main/java/com/moyorak/api/party/repository/PartyRestaurantRepository.java
  src/main/java/com/moyorak/api/party/repository/RandomVoteInfoRepository.java
  src/main/java/com/moyorak/api/party/repository/SelectionVoteInfoRepository.java
  src/main/java/com/moyorak/api/party/repository/VoteRecordRepository.java
  src/main/java/com/moyorak/api/party/repository/VoteRepository.java
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
  src/main/java/com/moyorak/api/party/service/PartyService.java
  src/main/java/com/moyorak/api/party/service/VoteRecordService.java
  src/main/java/com/moyorak/api/party/service/VoteService.java
  src/test/java/com/moyorak/api/party/domain/RandomVoteInfoFixture.java
  src/test/java/com/moyorak/api/party/domain/RandomVoteInfoTest.java
  src/test/java/com/moyorak/api/party/domain/SelectionVoteInfoFixture.java
  src/test/java/com/moyorak/api/party/domain/VoteFixture.java
  src/test/java/com/moyorak/api/party/domain/VoteRestaurantCandidateFixture.java
  src/test/java/com/moyorak/api/party/domain/VoteTest.java
  src/test/java/com/moyorak/api/party/service/VoteServiceTest.java
Labels: ✨ Feature

#248 feat: #243 파티 참여하기
  src/main/java/com/moyorak/api/party/controller/PartyAttendeeController.java
  src/main/java/com/moyorak/api/party/domain/PartyAttendee.java
  src/main/java/com/moyorak/api/party/dto/PartyAttendRequest.java
  src/main/java/com/moyorak/api/party/repository/PartyAttendeeRepository.java
  src/main/java/com/moyorak/api/party/repository/PartyRepository.java
  src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
  src/test/java/com/moyorak/api/party/domain/PartyFixture.java
  src/test/java/com/moyorak/api/party/service/PartyAttendeeServiceTest.java
Labels: ✨ Feature

#249 refactor: #247 파티 목록 조회 시, 상태 값 변경
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
  src/main/java/com/moyorak/api/party/service/VoteService.java
  src/test/java/com/moyorak/api/party/service/PartyFacadeTest.java
Labels: 🔨 Refactor

#251 feat: #244 파티 및 투표 생성 기능 추가
  src/main/java/com/moyorak/api/party/controller/PartyController.java
  src/main/java/com/moyorak/api/party/domain/Party.java
  src/main/java/com/moyorak/api/party/domain/PartyAttendee.java
  src/main/java/com/moyorak/api/party/domain/Vote.java
  src/main/java/com/moyorak/api/party/domain/VoteRestaurantCandidate.java
  src/main/java/com/moyorak/api/party/domain/VoteType.java
  src/main/java/com/moyorak/api/party/dto/PartySaveRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveRestaurantRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveRestaurantSelectionRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveRestaurantsRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveUserRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveUserSelectionRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveUsersRequest.java
  src/main/java/com/moyorak/api/party/dto/PartySaveVoteRequest.java
  src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
  src/main/java/com/moyorak/api/party/service/PartyRestaurantService.java
  src/main/java/com/moyorak/api/party/service/PartyService.java
  src/main/java/com/moyorak/api/party/service/VoteService.java
  src/main/java/com/moyorak/api/team/service/TeamService.java
  src/test/java/com/moyorak/api/party/domain/VoteTypeTest.java
  src/test/java/com/moyorak/api/party/dto/PartySaveVoteRequestFixture.java
  src/test/java/com/moyorak/api/party/dto/PartySaveVoteRequestTest.java
Labels: ✨ Feature

#201 feat: #127 회원 탈퇴 기능 추가
  src/main/java/com/moyorak/api/auth/controller/UserController.java
  src/main/java/com/moyorak/api/auth/domain/Gender.java
  src/main/java/com/moyorak/api/auth/domain/User.java
  src/main/java/com/moyorak/api/auth/domain/UserToken.java
  src/main/java/com/moyorak/api/auth/repository/MealTagRepository.java
  src/main/java/com/moyorak/api/auth/repository/UserRepository.java
  src/main/java/com/moyorak/api/auth/service/AuthService.java
  src/main/java/com/moyorak/api/auth/service/MealTagService.java
  src/main/java/com/moyorak/api/auth/service/UserFacade.java
  src/main/java/com/moyorak/api/auth/service/UserService.java
  src/main/java/com/moyorak/api/team/domain/TeamUser.java
  src/main/java/com/moyorak/api/team/repository/TeamUserRepository.java
  src/main/java/com/moyorak/api/team/service/TeamUserService.java
  src/test/java/com/moyorak/api/auth/domain/GenderTest.java
  src/test/java/com/moyorak/api/auth/domain/UserTokenTest.java
Labels: ✨ Feature

#262 refactor:#261 파티 목록 조회 시, 투표 종료 시간 추가
  src/main/java/com/moyorak/api/party/dto/PartyGeneralInfoProjection.java
  src/main/java/com/moyorak/api/party/dto/PartyListResponse.java
  src/main/java/com/moyorak/api/party/repository/PartyRepository.java
  src/test/java/com/moyorak/api/party/domain/PartyGeneralInfoProjectionFixture.java
  src/test/java/com/moyorak/api/party/service/PartyFacadeTest.java
Labels: 🔨 Refactor

#273 refactor: #272 파티 생성시, 투표 상세 정보도 함께 저장도록 기능 추가
  src/main/java/com/moyorak/api/party/domain/RandomVoteInfo.java
  src/main/java/com/moyorak/api/party/domain/SelectionVoteInfo.java
  src/main/java/com/moyorak/api/party/dto/PartySaveRequest.java
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
  src/main/java/com/moyorak/api/party/service/VoteService.java
Labels: 🔨 Refactor

#277 refactor: #276 회사 저장 시, 등록한 회사에 대한 ID 값을 반환하도록 수정
  src/main/java/com/moyorak/api/company/controller/CompanyController.java
  src/main/java/com/moyorak/api/company/dto/CompanySaveResponse.java
  src/main/java/com/moyorak/api/company/service/CompanyService.java
Labels: 🔨 Refactor

#270 refactor: #269 파티 상세 조회에서 참석 유무 응답 필드 추가
  src/main/java/com/moyorak/api/party/controller/PartyController.java
  src/main/java/com/moyorak/api/party/dto/PartyResponse.java
  src/main/java/com/moyorak/api/party/dto/Voter.java
  src/main/java/com/moyorak/api/party/dto/VoterResponse.java
  src/main/java/com/moyorak/api/party/repository/PartyAttendeeRepository.java
  src/main/java/com/moyorak/api/party/repository/VoteRecordRepository.java
  src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
Labels: 🔨 Refactor

#281 refactor: #279 파티 상세 조회 시 응답 dto 필드에 참여 가능 여부 필드 추가
  src/main/java/com/moyorak/api/party/controller/PartyController.java
  src/main/java/com/moyorak/api/party/domain/Party.java
  src/main/java/com/moyorak/api/party/dto/PartyInfo.java
  src/main/java/com/moyorak/api/party/dto/PartyResponse.java
  src/main/java/com/moyorak/api/party/service/PartyFacade.java
  src/main/java/com/moyorak/api/party/service/PartyService.java
Labels: 🔨 Refactor

#271 feat:#264 투표 기능 개발
  src/main/java/com/moyorak/api/party/controller/VoteController.java
  src/main/java/com/moyorak/api/party/domain/VoteRecord.java
  src/main/java/com/moyorak/api/party/dto/VoteRequest.java
  src/main/java/com/moyorak/api/party/repository/PartyRestaurantRepository.java
  src/main/java/com/moyorak/api/party/repository/VoteRecordRepository.java
  src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
  src/main/java/com/moyorak/api/party/service/PartyRestaurantService.java
  src/main/java/com/moyorak/api/party/service/VoteFacade.java
  src/main/java/com/moyorak/api/party/service/VoteRecordService.java
  src/main/java/com/moyorak/api/party/service/VoteService.java
  src/main/java/com/moyorak/api/team/service/TeamUserService.java
  src/test/java/com/moyorak/api/party/domain/PartyInfoFixture.java
  src/test/java/com/moyorak/api/party/domain/VoteRecordFixture.java
  src/test/java/com/moyorak/api/party/dto/VoteRequestFixture.java
  src/test/java/com/moyorak/api/party/service/VoteFacadeTest.java
Labels: ✨ Feature

#287 fix:#284 팀 맛집 리뷰 업데이트 쿼리 수정,리뷰 업데이트 시 이미지 수정 로직 변경
  src/main/java/com/moyorak/api/review/service/ReviewFacade.java
  src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
Labels: 🔨 Refactor, 🐞 Fix

#288 fix:#284 리뷰, 리뷰사진 조회 트랜잭션 변경, 팀 맛집 정보 음수 되지 못하게 변경
  src/main/java/com/moyorak/api/review/service/ReviewFacade.java
  src/main/java/com/moyorak/api/review/service/ReviewPhotoService.java
  src/main/java/com/moyorak/api/review/service/ReviewService.java
  src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
  src/test/java/com/moyorak/api/review/service/ReviewFacadeTest.java
Labels: 🔨 Refactor, 🐞 Fix

#289 fix:#284 벌크 업데이트 전 flush되게 변경
  src/main/java/com/moyorak/api/review/service/ReviewFacade.java
  src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
Labels: 🔨 Refactor, 🐞 Fix

#306 fix: #305 존재하는 팀 맛집만 조회하도록 페이징 처리
  src/main/java/com/moyorak/api/team/repository/TeamRestaurantRepository.java
  src/main/java/com/moyorak/api/team/service/TeamRestaurantService.java
Labels: 🐞 Fix

#311 fix: #310 팀 ID 비교 검증 로직 변경
  src/main/java/com/moyorak/api/party/service/PartyAttendeeService.java
Labels: 🐞 Fix

#307 refactor: #301 팀원 목록 조회에 팀 이름 추가
  src/main/java/com/moyorak/api/team/controller/TeamUserController.java
  src/main/java/com/moyorak/api/team/dto/TeamUserListResponse.java
  src/main/java/com/moyorak/api/team/service/TeamUserManagementService.java
Labels: 🔨 Refactor
